/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zinnia_Recognizer */

#ifndef _Included_org_zinnia_Recognizer
#define _Included_org_zinnia_Recognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zinnia_Recognizer
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Recognizer_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    nativeDelete
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zinnia_Recognizer_nativeDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    open
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zinnia_Recognizer_open__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    open
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zinnia_Recognizer_open__JLjava_lang_String_2J
  (JNIEnv *, jobject, jlong, jstring, jlong);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    close
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zinnia_Recognizer_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Recognizer_size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    value
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zinnia_Recognizer_value
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    classify
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Recognizer_classify
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_zinnia_Recognizer
 * Method:    what
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zinnia_Recognizer_what
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
