/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zinnia_Character */

#ifndef _Included_org_zinnia_Character
#define _Included_org_zinnia_Character
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zinnia_Character
 * Method:    nativeNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Character_nativeNew
  (JNIEnv *, jobject);

/*
 * Class:     org_zinnia_Character
 * Method:    nativeDelete
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zinnia_Character_nativeDelete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    set_value
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_zinnia_Character_set_1value
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_zinnia_Character
 * Method:    value
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zinnia_Character_value
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    set_width
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zinnia_Character_set_1width
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    set_height
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_zinnia_Character_set_1height
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    width
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Character_width
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    height
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Character_height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    clear
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zinnia_Character_clear
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    add
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_org_zinnia_Character_add
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     org_zinnia_Character
 * Method:    strokes_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Character_strokes_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    stroke_size
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_zinnia_Character_stroke_1size
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    x
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zinnia_Character_x
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    y
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_zinnia_Character_y
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_zinnia_Character
 * Method:    parse
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_zinnia_Character_parse
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_zinnia_Character
 * Method:    what
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_zinnia_Character_what
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
